### ISSUE TITLE
Issue with BYTE_ARRAY property length in V1.24 ?

### ISSUE THREAD

**Issue by bmw-biker** [klausahrenberg/WAdapter#3]
Hi Klaus

Could there be an issue with the WProperty getLength method regarding BYTE_ARRAY ?
I used the WThermostat clock with "Use fixed offset to UTC time" and "calculate day saving" for a long time. Back then for me it seemed that the automatic setting didn't work. Calculated day saving did work including V1.20m.

Then I recently updated to version 1.24 (thermostat and adapter) and again tried to input the 8 settings (STD_..., DST_...).
But if you open the settings page, only the first 4 (STD_...) appear correct even from the DEFAULT_DST_RULE.
I was able to follow the code write 8 bytes to a WProperty BYTE_ARRAY.

I'm an experienced SW developer - but here I come to my limits on how your intension is to set and retrieve the length of an array.
Currently for me it looks like you just get the size of the pointer "byte* asByteArray" ?  Which is 4 bytes on that machine.
I assume this is the reason for only showing 4 correct bytes in the settings.
- How would the size of a byte array be set with setByteArray ?  
- Does a byte array have a size byte or end #0 like cstr ?
- Wouldn't sizeof(newValue) in setByteArray also return just the pointer size of newValue ?

Now, after trying and testing I found that currently I could solve the problem. 
The automatic daytime feature in V1.24 seems working fine with my thermostats and network.

Btw, thanks a lot for the great job you do with WAdapter and WThermostat !  I'm very happy to be able to use it on 12 Thermostats 10x BHT002, 2x X7H (which I added myself).

Best regards
Torsten

**Comment by klausahrenberg** [comment]
WProperty::getLength should give the correct length of the byte array. It's not giving the length of the pointer (always 4), but the number of byte elements in the array. Code in getLength method is:
```
case BYTE_ARRAY:
        return (this->valueNull ? 0 : sizeof(value.asByteArray));
```
To your other questions:

> How would the size of a byte array be set with setByteArray ?

One example here
```
const byte* DEFAULT_PROP_ARRAY = (const byte[]){0, 0, 0, 0};
WProperty* property = new WProperty("ba", "ba", BYTE_ARRAY, "");
property->setByteArray(DEFAULT_PROP_ARRAY);
```
> Does a byte array have a size byte or end #0 like cstr ?

No. Use WProperty::getLength()
